data:extend(
{
	{
	type = "fluid",
	name = "iron-ore-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.3, g=0.9, b=0.9},
    flow_color = {r=0.1, g=0.9, b=0.9},
    icon = "pipe_everything/graphics/icon/iron-ore-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},
	{
	type = "fluid",
	name = "iron-plate-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.4, g=0.9, b=0.9},
    flow_color = {r=0.2, g=0.9, b=0.9},
    icon = "pipe_everything/graphics/icon/iron-plate-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},
	{
	type = "fluid",
	name = "stone-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.5, g=0.5, b=0.5},
    flow_color = {r=0.5, g=0.5, b=0.5},
    icon = "pipe_everything/graphics/icon/stone-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},
	{
	type = "fluid",
	name = "stone-brick-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.4, g=0.4, b=0.4},
    flow_color = {r=0.4, g=0.4, b=0.4},
    icon = "pipe_everything/graphics/icon/stone-brick-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},	
	{
	type = "fluid",
	name = "raw-wood-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.4, g=0.2, b=0.0},
    flow_color = {r=0.4, g=0.3, b=0.0},
    icon = "pipe_everything/graphics/icon/raw-wood-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},	
	{
	type = "fluid",
	name = "wood-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.4, g=0.2, b=0.0},
    flow_color = {r=0.4, g=0.3, b=0.0},
    icon = "pipe_everything/graphics/icon/wood-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},		
	{
	type = "fluid",
	name = "copper-ore-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.9, g=0.5, b=0.0},
    flow_color = {r=0.9, g=0.6, b=0.1},
    icon = "pipe_everything/graphics/icon/copper-ore-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},
	{
	type = "fluid",
	name = "copper-plate-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.9, g=0.5, b=0.1},
    flow_color = {r=0.9, g=0.6, b=0.2},
    icon = "pipe_everything/graphics/icon/copper-plate-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},
	{
	type = "fluid",
	name = "iron-stick-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.6, g=0.6, b=0.6},
    flow_color = {r=0.5, g=0.5, b=0.5},
    icon = "pipe_everything/graphics/icon/iron-stick-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},		
	{
	type = "fluid",
	name = "gear-wheel-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.6, g=0.6, b=0.6},
    flow_color = {r=0.5, g=0.5, b=0.5},
    icon = "pipe_everything/graphics/icon/gear-wheel-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},	
	{
	type = "fluid",
	name = "steel-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.8, g=0.8, b=0.8},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "pipe_everything/graphics/icon/steel-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},	
	{
	type = "fluid",
	name = "copper-cable-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.9, g=0.5, b=0.1},
    flow_color = {r=0.9, g=0.6, b=0.2},
    icon = "pipe_everything/graphics/icon/copper-cable-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},	
	{
	type = "fluid",
	name = "electronic-circuit-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.2, g=0.9, b=0.2},
    flow_color = {r=0, g=0.9, b=0},
    icon = "pipe_everything/graphics/icon/electronic-circuit-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},	
	{
	type = "fluid",
	name = "advanced-circuit-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.9, g=0.1, b=0.1},
    flow_color = {r=0.9, g=0, b=0},
    icon = "pipe_everything/graphics/icon/advanced-circuit-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},	
	{
	type = "fluid",
	name = "processing-unit-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0, g=0, b=0.5},
    flow_color = {r=0, g=0, b=0.3},
    icon = "pipe_everything/graphics/icon/processing-unit-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},	
	{
	type = "fluid",
	name = "sulfur-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.9, g=0.9, b=0},
    flow_color = {r=0.7, g=0.7, b=0},
    icon = "pipe_everything/graphics/icon/sulfur-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},	
	{
	type = "fluid",
	name = "plastic-bar-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.9, g=0.9, b=9},
    flow_color = {r=0.8, g=0.8, b=8},
    icon = "pipe_everything/graphics/icon/plastic-bar-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},	
	{
	type = "fluid",
	name = "robot-frame-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.6, g=0.6, b=0.6},
    flow_color = {r=0.5, g=0.5, b=0.5},
    icon = "pipe_everything/graphics/icon/robot-frames-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},
	{	
	type = "fluid",
	name = "battery-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.6, g=0.6, b=0.6},
    flow_color = {r=0.5, g=0.5, b=0.5},
    icon = "pipe_everything/graphics/icon/battery-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},	
	{	
	type = "fluid",
	name = "engine-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.8, g=0.8, b=0},
    flow_color = {r=0.6, g=0.6, b=0},
    icon = "pipe_everything/graphics/icon/engine-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},
	{	
	type = "fluid",
	name = "electronic-engine-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.8, g=0, b=0},
    flow_color = {r=0.6, g=0, b=0},
    icon = "pipe_everything/graphics/icon/electronic-engine-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},
	{	
	type = "fluid",
	name = "explosives-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.2, g=0, b=0},
    flow_color = {r=0.1, g=0, b=0},
    icon = "pipe_everything/graphics/icon/explosives-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},
	--modules
	--speed modules
		{	
	type = "fluid",
	name = "speed-module-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0, g=0, b=0.5},
    flow_color = {r=0, g=0, b=0.5},
    icon = "pipe_everything/graphics/icon/speed-module-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},
	{	
	type = "fluid",
	name = "speed-module-2-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0, g=0, b=0.5},
    flow_color = {r=0, g=0, b=0.5},
    icon = "pipe_everything/graphics/icon/speed-module-2-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},
	{	
	type = "fluid",
	name = "speed-module-3-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0, g=0, b=0.5},
    flow_color = {r=0, g=0, b=0.5},
    icon = "pipe_everything/graphics/icon/speed-module-3-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},
	--efficiency modules
	{	
	type = "fluid",
	name = "effectivity-module-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0, g=0.5, b=0},
    flow_color = {r=0, g=0.5, b=0},
    icon = "pipe_everything/graphics/icon/effectivity-module-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},
	{	
	type = "fluid",
	name = "effectivity-module-2-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0, g=0.5, b=0},
    flow_color = {r=0, g=0.5, b=0},
    icon = "pipe_everything/graphics/icon/effectivity-module-2-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},
	{	
	type = "fluid",
	name = "effectivity-module-3-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0, g=0.5, b=0},
    flow_color = {r=0, g=0.5, b=0},
    icon = "pipe_everything/graphics/icon/effectivity-module-3-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},	
	--productivity modules
	{	
	type = "fluid",
	name = "productivity-module-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.8, g=0, b=0.8},
    flow_color = {r=0.8, g=0, b=0.8},
    icon = "pipe_everything/graphics/icon/productivity-module-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},
	{	
	type = "fluid",
	name = "productivity-module-2-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.8, g=0, b=0.8},
    flow_color = {r=0.8, g=0, b=0.8},
    icon = "pipe_everything/graphics/icon/productivity-module-2-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},
	{	
	type = "fluid",
	name = "productivity-module-3-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.8, g=0, b=0.8},
    flow_color = {r=0.8, g=0, b=0.8},
    icon = "pipe_everything/graphics/icon/productivity-module-3-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},	
	--/modules
	{	
	type = "fluid",
	name = "low-density-structure-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.2, g=0, b=0},
    flow_color = {r=0.1, g=0, b=0},
    icon = "pipe_everything/graphics/icon/rocket-structure-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},
	{	
	type = "fluid",
	name = "solid-fuel-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.2, g=0.2, b=0.2},
    flow_color = {r=0.1, g=0.1, b=0.1},
    icon = "pipe_everything/graphics/icon/solid-fuel-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},	
	{	
	type = "fluid",
	name = "rocket-fuel-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.8, g=0.8, b=0.8},
    flow_color = {r=0.8, g=0.8, b=0.8},
    icon = "pipe_everything/graphics/icon/rocket-fuel-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},
	{	
	type = "fluid",
	name = "rocket-control-unit-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.8, g=0, b=0.4},
    flow_color = {r=0.8, g=0, b=0.3},
    icon = "pipe_everything/graphics/icon/rocket-control-unit-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},
	{	
	type = "fluid",
	name = "alien-artifact-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.9, g=0, b=0.3},
    flow_color = {r=0.9, g=0, b=0.2},
    icon = "pipe_everything/graphics/icon/alien-artifact-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},	
	{	
	type = "fluid",
	name = "science-one-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.9, g=0, b=0},
    flow_color = {r=0.8, g=0, b=0},
    icon = "pipe_everything/graphics/icon/science-one-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},
	{	
	type = "fluid",
	name = "science-two-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0, g=0.9, b=0},
    flow_color = {r=0, g=0.8, b=0},
    icon = "pipe_everything/graphics/icon/science-two-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},
	{	
	type = "fluid",
	name = "science-three-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0, g=0, b=0.9},
    flow_color = {r=0, g=0, b=0.8},
    icon = "pipe_everything/graphics/icon/science-three-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	},
	{	
	type = "fluid",
	name = "science-four-fluid",
	default_temperature = 25,
	max_temperature = 100,
	heat_capacity = "1KJ",
    base_color = {r=0.4, g=0, b=0.8},
    flow_color = {r=0.5, g=0, b=0.9},
    icon = "pipe_everything/graphics/icon/science-four-fluid.png",
    order = "a[fluid]-i[diesel-fuel]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
	}
})